"services":
  "blog-hugo":
    "build":
      "args":
      - "HUGO_VERSION=0.60.1"
      - "HUGO_TYPE=_extended"
      - "HUGO_HOME=/hugo"
      "context": "src/main/hugo"
      "dockerfile": "Dockerfile"
    "command": "make all"
    "env_file": ".env"
    "image": "blog-hugo:0.60.1"
    "ports":
    - "1313"
    "restart": "always"
    "volumes":
    - "./src/main/hugo:/hugo:ro"
    - "./output/hugo/public:/srv/hugo/output:rw"
    - "./content:/srv/hugo/content:ro"
    - "./cache/hugo/resources:/hugo/src/resources:rw"
  "blog-proxy":
    "build":
      "context": "src/main/proxy"
      "dockerfile": "Dockerfile"
    "command": "make all"
    "container_name": "blog-proxy"
    "depends_on":
    - "blog-hugo"
    "env_file": ".env"
    "image": "blog-proxy:1.0"
    "ports":
    - "80:80"
    - "8080:8080"
    "restart": "always"
    "volumes":
    - "./src/main/proxy:/nginx:ro"
    - "./src/main/proxy/src/conf.d:/etc/nginx/conf.d:ro"
"version": "3.7"

