version: "3.7"

services:
  blog-hugo:
    container_name: blog-hugo
    image: 'blog-hugo:${HUGO_VERSION}'
    build:
      context: src/main/hugo
      dockerfile: Dockerfile
      args:
        - HUGO_VERSION=${HUGO_VERSION}
        - HUGO_TYPE=${HUGO_TYPE}
        - HUGO_HOME=${HUGO_HOME}
    volumes:
      - ./${HOST_HUGO_ROOT}:${HUGO_HOME}:ro
      - ./${HOST_HUGO_OUTPUT}:${HUGO_OUTPUT}:rw
      - ./${HOST_HUGO_CONTENT}:${HUGO_CONTENT}:ro
      - ./${HOST_HUGO_CACHE}:${HUGO_RESOURCES}:rw
    restart: always
    ports:
      - 1313
    command: "make all"
    env_file: .env

  blog-proxy:
    container_name: blog-proxy
    image: blog-proxy:1.0
    env_file: .env
    command: "make all"
    restart: always
    build:
      context: src/main/proxy
      dockerfile: Dockerfile
    volumes:
      - ./${HOST_PROXY_ROOT}:/nginx:ro
      - ./${HOST_PROXY_CONFD}:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - blog-hugo

