version: "3.7"

services:
  web-hugo-blog:
    container_name: ${HUGO_BLOG_NAME}
    image: '${HUGO_BLOG_NAME}:${HUGO_VERSION_BLOG}'
    build:
      context: src/main/hugo
      dockerfile: Dockerfile
      args:
        - HUGO_VERSION=${HUGO_VERSION_BLOG}
        - HUGO_TYPE=${HUGO_TYPE}
        - HUGO_HOME=${HUGO_HOME}
    volumes:
      - ./${HOST_HUGO_ROOT}:${HUGO_HOME}:ro
      - ./${HOST_HUGO_OUTPUT_BLOG}:${HUGO_OUTPUT_BLOG}:rw
      - ./${HOST_HUGO_CONTENT_BLOG}:${HUGO_CONTENT}:ro
      - ./${HOST_HUGO_CACHE}:${HUGO_RESOURCES}:rw
    env_file: .env
    environment:
      - HUGO_ENV=blog
      - HUGO_WEB_NAME=${HUGO_BLOG_NAME}
      - HUGO_BASEURL=${HUGO_BASEURL_BLOG}
      - HUGO_VERSION=${HUGO_VERSION_BLOG}
      - HUGO_OUTPUT=${HUGO_OUTPUT_BLOG}
      - HUGO_THEME=${HUGO_THEME_BLOG}
      - HUGO_PORT=${HUGO_PORT_BLOG}
    restart: always
    ports:
      - 1313
    command: "make all"
  web-hugo-docs:
    container_name: ${HUGO_NOTEBOOK_NAME}
    image: '${HUGO_NOTEBOOK_NAME}:${HUGO_VERSION_NOTEBOOK}'
    build:
      context: src/main/hugo
      dockerfile: Dockerfile
      args:
        - HUGO_VERSION=${HUGO_VERSION_NOTEBOOK}
        - HUGO_TYPE=${HUGO_TYPE}
        - HUGO_HOME=${HUGO_HOME}
    volumes:
      - ./${HOST_HUGO_ROOT}:${HUGO_HOME}:ro
      - ./${HOST_HUGO_OUTPUT_NOTEBOOK}:${HUGO_OUTPUT_NOTEBOOK}:rw
      - ./${HOST_HUGO_CONTENT_NOTEBOOK}:${HUGO_CONTENT}:ro
      - ./${HOST_HUGO_CACHE}:${HUGO_RESOURCES}:rw
    restart: always
    ports:
      - 1313
    command: "make all"
    env_file: .env
    environment:
      - HUGO_ENV=docs
      - HUGO_WEB_NAME=${HUGO_NOTEBOOK_NAME}
      - HUGO_BASEURL=${HUGO_BASEURL_NOTEBOOK}
      - HUGO_VERSION=${HUGO_VERSION_NOTEBOOK}
      - HUGO_OUTPUT=${HUGO_OUTPUT_NOTEBOOK}
      - HUGO_THEME=${HUGO_THEME_NOTEBOOK}
      - HUGO_PORT=${HUGO_PORT_NOTEBOOK}
  web-proxy:
    container_name: web-proxy
    image: blog-proxy:1.0
    env_file: .env
    command: "make all"
    restart: always
    build:
      context: src/main/proxy
      dockerfile: Dockerfile
    volumes:
      - ./${HOST_PROXY_ROOT}:/nginx:ro
      - ./${HOST_PROXY_CONFD}:/etc/nginx/conf.d:rw
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - web-hugo-blog
      - web-hugo-docs

