baseURL = "http://www.onceawaken.com"
title = "Onceawaken"
# for smart copyright line, leave this blank and check [params.copyright]
canonifyUrl = true #
theme = "zzo"

ignoreFiles = [ ".md.$", ".idea", ".vscode", "webs",  "literature", "github", "codes",  ".tutorials", ".rawdata", ".ipynb", ".zip", ".tgz", ".tar.gz" ]

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

summaryLength = 70
buildFuture = true

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
enableKatex = true
paginate = 30
rssLimit = 100

preserveTaxonomyNames = true
# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
# pygmentsCodefences = true

enableRobotsTXT = true # generate robots.txt
enableGitInfo = false
googleAnalytics = ""

##
disableKinds = ["taxonomyTerm"]


[markup]
#  defaultMarkdownHandler = "goldmark"
  defaultMarkdownHandler = "blackFriday"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false
    lineNumbersInTable = true
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    ordered = true
    startLevel = 1

[outputs]
  page = ["HTML", "SearchIndex"]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"