[en]
  title = "Onceawaken"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[pl]
  title = "Onceawaken"
  languageName = "Polish"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/pl"
