baseURL = "http://www.onceawaken.com"
title = "Onceawaken"
# for smart copyright line, leave this blank and check [params.copyright]
theme = "zdoc"
canonifyUrl = false#



[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

