main:
  - identifier: "blog"
    name: "[Blog]"
    url: "http://localhost/"
    weight: 1
  - identifier: "notebook"
    name: "Docs"
    url: "notebook"
    weight: 1
  - identifier: "posts"
    name: "Posts"
    url: "posts"
    weight: 2
  - identifier: "updates"
    name: "Updates"
    url: "updates"
    weight: 100




